sonar.organization=oualiroudaina
sonar.projectKey=OualiRoudaina_TP
sonar.projectName=Mon Projet React Node

sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/__tests__/**/*
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
